In [1]:
import numpy as np

ndarr = np.array([3, 4, -5])  

print(ndarr)
print(ndarr.size)  # 資料數量

[ 3  4 -5]
3


In [22]:
#建立一維資料

data = np.zeros(3)
data11 = np.empty(4)
data12 = np.ones(3)     #3個資料為一的陣列
data13 = np.arange(5) 
data14 = np.array([3,4,5,6,7])
#print(data14)

#建立二維資料
data21 = np.array([         #3*3的二維陣列
    [2,3,4],
    [3,4,5],
    [4,5,6]
])         

data22 = np.empty([3,3])    #3*3未指定資料的陣列
data23 = np.ones([2,3])
#print(data23)

#建立三維陣列
data31 = np.array([
    [  [1,2,3],[4,5,6]

    ],
    [  [7,8,9],[2,3,3]

    ]
])
data32 = np.empty([2,2,3])
#print(data32)

#建立高維陣列
data41 = np.array([    #1*2*2*2
    [
        [[3,1]],[[2,3]]
    ],
    [
        [[6,6]],[[8,7]]
    ]
])

data42 = np.ones([1,2,2,2])
print(data42)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


In [4]:
import sympy


NameError: name 'x' is not defined