In [2]:
import numpy as np

ndarr = np.array([3, 4, -5])  

print(ndarr)
print(ndarr.size)  # 資料數量

[ 3  4 -5]
3


In [22]:
#建立一維資料

data = np.zeros(3)
data11 = np.empty(4)
data12 = np.ones(3)     #3個資料為一的陣列
data13 = np.arange(5) 
data14 = np.array([3,4,5,6,7])
#print(data14)

#建立二維資料
data21 = np.array([         #3*3的二維陣列
    [2,3,4],
    [3,4,5],
    [4,5,6]
])         

data22 = np.empty([3,3])    #3*3未指定資料的陣列
data23 = np.ones([2,3])
#print(data23)

#建立三維陣列
data31 = np.array([
    [  [1,2,3],[4,5,6]

    ],
    [  [7,8,9],[2,3,3]

    ]
])
data32 = np.empty([2,2,3])
#print(data32)

#建立高維陣列
data41 = np.array([    #1*2*2*2
    [
        [[3,1]],[[2,3]]
    ],
    [
        [[6,6]],[[8,7]]
    ]
])

data42 = np.ones([1,2,2,2])
print(data42)

[[[[1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]]]]


In [23]:
#陣列運算
data1 = np.array([3,4,5])
data2 = np.array([4,5,6])
result = data1 + data2
#print(result)
#---------------------------------------------------
#矩陣運算
matrix1 = np.array(    #1*2matrix
    [2,5]
)
matrix2 = np.array([    #2*3matrix
    [3,5,4],
    [2,3,6]
])

#result = matrix1.dot(matrix2)  #1*3  # result= matrix1@matrix2   #內積
result = matrix1@matrix2
result2 = np.outer(matrix1,matrix2)  #2*6  #外積   #matrix1的第一個元素乘上matrix2的所有元素形成第一排,依此類推
#print(result2)
#-----------------------------------------------------------
#統計計算
datastat = np.array([
    [2,3,4],
    [-4,5,6]
])
result3 = datastat.sum()  #總和
result4 = datastat.max()  #最大值  min最小值
result5 = datastat.mean() #平均數
result6 = datastat.std()  #標準差
result31 = datastat.sum(axis=0)  #針對欄去做總和 column  #0為行  1為列
result32 = datastat.sum(axis=1)  #針對列去做總和 row
result7 = datastat.cumsum(axis=0) #逐值累加
print(result7)

[[ 2  3  4]
 [-2  8 10]]


In [ ]:
data = np.array([
    [2,3,4],
    [3,4,5]
])

In [27]:
np.zeros(shape=(2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

### 多維度操作

# 多維度操作
- A
1. AAAA

In [3]:
data41 = np.array([    #2*2*1*2
    [
        [[3,1]],[[2,3]]
    ],
    [
        [[6,6]],[[8,7]]
    ]
])

aaa = np.array([
    [1,2,3,4,5]
])

print(aaa.shape)   #shape=size 1*5的向量
print(data41[:,:,0,0])


(1, 5)
[[3 2]
 [6 8]]


In [8]:
#測試資料
arr1 = np.array([          #2*3
    [1,2,3],
    [4,5,6]
])

arr2 = np.array([          #2*3
    [7,8,9],
    [10,11,12]
])

resulta = np.vstack((arr1,arr2))  #vstack = 合併第一個維度  #變4*3
resultb = np.hstack((arr1,arr2))  #hstack = 合併第二個維度  #變2*6
print(resultb)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [12]:
#測試資料
arr3 = np.array([     #2*6
    [2,4,6,8,10,12],
    [1,3,5,7,9,11]
])

#根據第一個維度切割
resultc = np.vsplit(arr3,2)  #2*6變成 1*6 1*6
#print(resultc)

#根據第二個維度切割
resultd = np.hsplit(arr3,2)   #2*6變成 2*3 2*3
print(resultd)

[array([[2, 4, 6],
       [1, 3, 5]]), array([[ 8, 10, 12],
       [ 7,  9, 11]])]
